sudo: false

language: python

python:
    - "2.7"
    - "3.4"

install:
  - pip install .
  - pip install coverage

script:
  - cd test
  - nosetests --with-coverage --cover-package=decimal2rational

after_success:
  - bash <(curl -s https://codecov.io/bash)
