sudo: true
dist: trusty

language: python

python:
    - "2.7"
    - "3.4"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt install python-pytest python-pytest-cov python3-pytest python3-pytest-cov

install:
  - pip install .

script:
  - cd test
  - pytest --cov dedec

after_success:
  - bash <(curl -s https://codecov.io/bash)
